common:
  cookie_secret: '73f4e2645t2dssd51b85d633bcb4307'
  db_type: '[DB_TYPE]'
  db_host: 'localhost'
  db_port: 3306
  db_user: '[PROJECT]'
  db_pass: '[PROJECT]'  
production:
  db_name: '[PROJECT]'
staging:
  db_user: '[PROJECT]'
  db_pass: '[PROJECT]'
  db_name: '[PROJECT]_staging'
test:
  db_name: '[PROJECT]_test'
development:
  db_name: '[PROJECT]_dev'
